# Generated by Django 4.2.5 on 2024-01-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catgory", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("stock", models.IntegerField()),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="images")),
            ],
        ),
    ]
