# Generated by Django 4.2.5 on 2024-01-31 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="catgory",
            new_name="category",
        ),
    ]
