# Generated by Django 4.2.5 on 2024-01-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_catgory_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
