# Generated by Django 4.2.5 on 2024-02-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_order_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="user",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
