# Generated by Django 4.2.5 on 2024-02-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_cartitem_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(to="main.cartitem"),
        ),
    ]
