# Generated by Django 4.2.5 on 2024-02-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_order_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="receipt",
            field=models.FileField(blank=True, null=True, upload_to="receipts/"),
        ),
    ]
