# Generated by Django 4.2.5 on 2024-02-03 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_order_receipt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="session_key",
        ),
    ]
