# Generated by Django 4.2.5 on 2024-02-03 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_remove_cartitem_session_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="image",
        ),
        migrations.CreateModel(
            name="ItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.item"
                    ),
                ),
            ],
        ),
    ]
