# Generated by Django 4.2.5 on 2024-02-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_item_description_alter_item_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="size",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
