# Generated by Django 4.2.5 on 2024-02-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_remove_order_items_cartitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_summary",
            field=models.TextField(blank=True),
        ),
    ]
