# Generated by Django 4.2.5 on 2024-02-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
