# Generated by Django 4.2.5 on 2024-02-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
