# Generated by Django 4.2.5 on 2024-02-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_order_shipping_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_option",
            field=models.CharField(
                blank=True,
                choices=[("delivery", "Delivery +$10"), ("pickup", "Pickup")],
                max_length=10,
            ),
        ),
    ]
